version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - nature-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - nature-network

networks:
  nature-network:
    driver: bridge
