sonar.projectKey=jamartinezv2023_nature
sonar.organization=jamartinezv2023

sonar.projectName=nature
sonar.projectVersion=1.0

sonar.sources=src,public,routes
sonar.tests=tests

sonar.language=php

sonar.sourceEncoding=UTF-8

# Exclusiones
sonar.exclusions=vendor/**,storage/**,bootstrap/**,public/assets/**

# Cobertura
sonar.php.coverage.reportPaths=coverage.xml

# Quality Gate
sonar.qualitygate.wait=true
